package Presentacion.vistas.vistaAlquiler;

import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import Negocio.Alquiler.TAlquiler;
import Presentacion.comandos.listadecomandos.ListaComandos;
import Presentacion.controlador.Controller;
import Presentacion.vistas.vistaCalendario.Calendario;

public class AlquilerGUI extends javax.swing.JFrame {

    /**
     * Creates new form Alquiler
     */
    public AlquilerGUI() {
    	setIconImage(new ImageIcon(getClass().getResource("/Imagenes/MotorLand.png")).getImage());
    	setTitle("Menú Alquiler");
        initComponents();
    }
    
    public void muestraAlquileres(TAlquiler... alquileres) {
    	for (TAlquiler t : alquileres) {
			alquilerTA.append(t.toString());
		}
    }
    public void limpiaCampos() {
    	 idATF.setText("");
         idCTF.setText(""); 
         alquilerTA.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        metodoPagoBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        altaAB = new javax.swing.JButton();
        modificaAB = new javax.swing.JButton();
        bajaAB = new javax.swing.JButton();
        consultaAB = new javax.swing.JButton();
        listaAB = new javax.swing.JButton();
        volverB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alquilerTA = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idATF = new javax.swing.JTextField();
        idCTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tarjetaRB = new javax.swing.JRadioButton();
        efectivoRB = new javax.swing.JRadioButton();
        limpiarB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        altaAB.setText("Alta Alquiler");
        altaAB.setToolTipText("Crea un nuevo alquiler en el sistema.");
        altaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaABActionPerformed(evt);
            }
        });

        modificaAB.setText("Modificar Alquiler");
        modificaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaABActionPerformed(evt);
            }
        });

        bajaAB.setText("Baja Alquiler");
        bajaAB.setToolTipText("Inactiva un alquiler en el sistema.");
        bajaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaABActionPerformed(evt);
            }
        });

        consultaAB.setText("Consultar Alquiler");
        consultaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaABActionPerformed(evt);
            }
        });

        listaAB.setText("Listar Alquileres");
        listaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaABActionPerformed(evt);
            }
        });

        volverB.setText("Volver");
        volverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(altaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bajaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(volverB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        alquilerTA.setEditable(false);
        alquilerTA.setColumns(20);
        alquilerTA.setRows(5);
        jScrollPane1.setViewportView(alquilerTA);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("ID Alquiler:");

        jLabel2.setText("ID Cliente:");

        jLabel3.setText("Metodo de pago:");

        metodoPagoBG.add(tarjetaRB);
        tarjetaRB.setActionCommand("Tarjeta");
        tarjetaRB.setText("Tarjeta");

        metodoPagoBG.add(efectivoRB);
        efectivoRB.setSelected(true);
        efectivoRB.setActionCommand("Efectivo");
        efectivoRB.setText("Efectivo");

        limpiarB.setText("Limpiar");
        limpiarB.setToolTipText("Vacía todos los campos de datos.");
        limpiarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(382, 382, 382))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarjetaRB)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(efectivoRB)
                                .addGap(95, 95, 95)
                                .addComponent(limpiarB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idATF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idCTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarjetaRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(efectivoRB)
                    .addComponent(limpiarB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridLayout(2,2));
        
        jLabel4.setText("Fecha Inicial");
        jLabel5.setText("Fecha Final");
        
        calendarioI = new Calendario(); 
        calendarioF = new Calendario();
        
        jPanel4.add(jLabel4);
        jPanel4.add(calendarioI.getCal());
        jPanel4.add(jLabel5);
        jPanel4.add(calendarioF.getCal());
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void limpiarBActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	limpiaCampos();
    }                                        

    private void altaABActionPerformed(java.awt.event.ActionEvent evt) {         
     	String idC = idCTF.getText();
     	int id_c;
     	Calendar fechaI; 
     	Calendar fechaF; 
     	String pago = ""; 
     	if((metodoPagoBG.getSelection().getActionCommand().equals("Tarjeta")) ? true : false)
     		pago = "TARJETA";
     	else
     		pago = "EFECTIVO";
     	
     	if (idC.isEmpty() || calendarioI.isEmpty() || calendarioF.isEmpty())
     		JOptionPane.showMessageDialog(null, "Error al dar de alta alquiler. Faltan campos por rellenar");
     	else {
     		try {
	     		fechaI = calendarioI.getFecha();
	     		fechaF = calendarioF.getFecha();
	     		if (fechaF.compareTo(fechaI) < 0)
	     			JOptionPane.showMessageDialog(null, "Error al dar de alta alquiler. "
	     					+ "La fecha de inicio debe ser menor que la fecha de fin.");
	     		else {
		     		id_c = Integer.parseInt(idC);
		     		if(id_c >= 0) {
			     		TAlquiler t = new TAlquiler(-1, id_c, fechaI, fechaF, -1, pago, true);
			     		
			     		Controller.getInstance().run(ListaComandos.VISTAMENUALTAALQUILEREMERGENTE, t);
			     		Controller.getInstance().run(ListaComandos.MOSTRAR_VEHICULOS_DISPONIBLES, t);
		     		}
		     		else
		     			JOptionPane.showMessageDialog(this, "El ID debe ser mayor que cero.", "Error alta alquiler", JOptionPane.ERROR_MESSAGE);
	     		}
     		}
     		catch(NumberFormatException e) {
     			JOptionPane.showMessageDialog(this, "El formato de los IDs es incorrecto", "Error alta alquiler", JOptionPane.ERROR_MESSAGE);
     		}
     	}
    }                                      

    private void bajaABActionPerformed(java.awt.event.ActionEvent evt) {  
    	int id; 
    	try {
    		id = Integer.parseInt(idATF.getText());
    		if (id >= 0)
    			Controller.getInstance().run(ListaComandos.NEGOCIOBAJAALQUILER, id);
    		else
    			JOptionPane.showMessageDialog(this, "El ID debe ser mayor que cero.", "Error baja alquiler", JOptionPane.ERROR_MESSAGE);
    	}
    	catch(NumberFormatException e) {
    		JOptionPane.showMessageDialog(this, "El formato de los IDs es incorrecto.", "Error baja alquiler", JOptionPane.ERROR_MESSAGE);
    	}
    	
    	
    }                                      

    private void modificaABActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void consultaABActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	int id; 
    	try {
    		id = Integer.parseInt(idATF.getText());
    		if (id >= 0)
    			Controller.getInstance().run(ListaComandos.NEGOCIOBUSCARALQUILER, id);
    		else
    			JOptionPane.showMessageDialog(this, "El ID debe ser mayor que cero.", "Error consulta alquiler", JOptionPane.ERROR_MESSAGE);
    	}
    	catch(NumberFormatException e) {
    		JOptionPane.showMessageDialog(this, "El formato del ID es incorrecto.", "Error consulta alquiler", JOptionPane.ERROR_MESSAGE);
    	}
    }                                          

    private void listaABActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void volverBActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //hay que añadir llamada al controlador venta principal
        this.setVisible(false);        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlquilerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea alquilerTA;
    private javax.swing.JButton altaAB;
    private javax.swing.JButton bajaAB;
    private javax.swing.JButton consultaAB;
    private javax.swing.JRadioButton efectivoRB;
    private javax.swing.JTextField idATF;
    private javax.swing.JTextField idCTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarB;
    private javax.swing.JButton listaAB;
    private javax.swing.ButtonGroup metodoPagoBG;
    private javax.swing.JButton modificaAB;
    private javax.swing.JRadioButton tarjetaRB;
    private javax.swing.JButton volverB;
    
    private Calendario calendarioI;
    private Calendario calendarioF; 
    // End of variables declaration                   
}